version: '3.4'

services:
    postgresql-database:
        container_name: "database_clinica"
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=MiGataSeLlamaGata
            - POSTGRES_DB=ClinicaVeterinariaTFG
        ports:
            - '5432:5432'
        volumes:
            - database_clinica:/var/lib/postgresql/data

volumes:
    database_clinica:
